# upload all local artifacts to s3 storage
push:
  aws s3 sync ./artifacts/ s3://penumbra-labs-artifact-storage/ --acl public-read

# push all artifacts to PL-hosted storage box
push-legacy:
  # rsync -a -e ssh --rsync-path 'sudo rsync' --partial-dir=.rsync-partial --info=progress2 ./artifacts/ artifacts.plinfra.net:/mnt/artifacts_1/artifacts/ --checksum
  rsync -a -e ssh --rsync-path 'sudo rsync' --partial-dir=.rsync-partial --info=progress2 ./artifacts/ artifacts.plinfra.net:/mnt/artifacts_1/artifacts/

# synchronize all artifacts to localhost; WARNING, requires several TB of disk space!
pull:
  aws s3 sync --endpoint-url https://nyc3.digitaloceanspaces.com s3://penumbra-labs-artifact-storage/ ./artifacts/ --no-sign-request

# find possible duplicate files
fdupes:
  fclones group .

# display recently changed files
recent:
  fd --no-ignore --changed-within 1w

# configure dummy auth
dummy-auth:
  aws configure set aws_access_key_id dummy
  aws configure set aws_secret_access_key dummy
  aws configure set default.region us-east-1
