//! Kubernetes-specific Custom Resource Definition for representing
//! Penumbra concepts, like [PenumbraNode].

use kube::runtime::controller::Action;
use kube_derive::CustomResource;
use schemars::JsonSchema;

use k8s_openapi::apimachinery::pkg::apis::meta::v1::LabelSelector;
use k8s_openapi::apimachinery::pkg::apis::meta::v1::ObjectMeta;
use k8s_openapi::apimachinery::pkg::util::intstr::IntOrString;
use std::time::Duration;

use serde::{Deserialize, Serialize};

// Declare a StatefulSet for Penumbra node.
use k8s_openapi::api::apps::v1::{StatefulSet, StatefulSetSpec};
use k8s_openapi::api::core::v1::{
    ConfigMap, Container, ContainerPort, EnvVar, PersistentVolumeClaim, PersistentVolumeClaimSpec,
    PodSpec, PodTemplateSpec, Probe, SecurityContext, Service, ServicePort, ServiceSpec,
    TCPSocketAction, VolumeMount, VolumeResourceRequirements,
};

use rand::Rng;
use rand_core::OsRng;

use k8s_openapi::apimachinery::pkg::api::resource::Quantity;
use kube::{
    api::{Api, DeleteParams, Patch, PatchParams, PostParams},
    Client,
};
use std::collections::BTreeMap;

use crate::error::Result;
use crate::resources;
use crate::DEFAULT_NAMESPACE;
use crate::PENUMBRA_IMAGE_REPO;
use crate::PENUMBRA_IMAGE_TAG;

/// The CometBFT RPC URL for the PenumbraNode whose network we want to join.
const DEFAULT_BOOTSTRAP_URL: &str = "https://rpc.testnet-preview.plinfra.net";

/// K8s CRD specification for a [`PenumbraNode`] resource.
///
/// Constitutes the `spec` field of a [PenumbraNode].
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
    group = "penumbra.zone",
    version = "v1alpha1",
    kind = "PenumbraNode",
    plural = "penumbranodes",
    derive = "PartialEq",
    namespaced,
    printcolumn = r#"{"name":"NetworkName", "type":"string", "jsonPath":".spec.network_name"}"#
)]
pub struct PenumbraNodeSpec {
    /// Human-readable name for node.
    moniker: String,
    /// Human-readable name for the network, as an arbitrary label,
    /// e.g. "penumbra-preview", rather than a chain-id.
    /// This value is used solely to distinguish the k8s resources,
    /// marking them explicitly as part of a greater whole.
    network_name: Option<String>,
    /// Container image spec, without tag suffix.
    image_repo: Option<String>,
    /// Container image tag to fetch from remote `image_repo`.
    image_tag: Option<String>,
    /// Public RPC endpoint for an already-existing remote node,
    /// to fetch information about the network.
    bootstrap_url: String,
    /// Remote URL to fetch a state archive, for extracting pre-upgrade blocks.
    archive_url: Option<String>,
    /// Whether to enable ABCI event indexing via CometBFT to a PostgreSQL database.
    enable_indexing: Option<bool>,
}

impl Default for PenumbraNodeSpec {
    fn default() -> Self {
        Self {
            moniker: crate::crd::moniker(),
            image_repo: Some(crate::PENUMBRA_IMAGE_REPO.to_owned()),
            image_tag: Some(crate::PENUMBRA_IMAGE_TAG.to_owned()),
            bootstrap_url: String::from(DEFAULT_BOOTSTRAP_URL),
            archive_url: None,
            network_name: None,
            enable_indexing: Some(false),
        }
    }
}

/// Generate likely-unique moniker in the form of `node-xxxxx`, where `xxxxx`
/// is a random string.
pub fn moniker() -> String {
    format!("node-{}", hex::encode(OsRng.gen::<u32>().to_le_bytes()))
}

impl PenumbraNode {
    /// Creates a likely-unique name for this node's resources.
    pub fn release_name(&self) -> String {
        format!("penumbra-node-{}", self.spec.moniker)
    }

    /// Emit a [StatefulSet] that matches the configured CRD.
    ///
    /// This function aggregates all the subcomponents of a StatefulSet,
    /// e.g. PodSpec, Pod, Container, VolumeClaimTemplate, etc.,
    /// and bottles them up into a single StatefulSet.
    pub fn stateful_set(&self) -> StatefulSet {
        let init_container = self.pd_init_container();

        let mut containers = vec![self.pd_container(), resources::cometbft_container()];
        // Opt in to ABCI event indexing
        if self.spec.enable_indexing.unwrap_or_default() {
            containers.push(resources::postgres_container());
        }
        StatefulSet {
            metadata: ObjectMeta {
                name: Some(self.release_name()),
                // TODO: Does this clobber annotations automatically generated by `kube`?
                annotations: Some(crate::resources::annotations()),
                ..Default::default()
            },
            spec: Some(StatefulSetSpec {
                replicas: Some(1),
                template: PodTemplateSpec {
                    metadata: Some(ObjectMeta {
                        name: Some(self.release_name()),
                        labels: Some(resources::labels()),
                        ..Default::default()
                    }),
                    spec: Some(PodSpec {
                        init_containers: Some(vec![init_container]),
                        containers,
                        volumes: Some(resources::volumes()),
                        ..Default::default()
                    }),
                },
                volume_claim_templates: Some(self.volume_claim_templates()),
                selector: LabelSelector {
                    match_labels: Some(resources::labels()),
                    ..Default::default()
                },
                ..Default::default()
            }),
            ..Default::default()
        }
    }

    /// Emit a [Service] for the configured CRD.
    pub fn service(&self) -> Service {
        let mut ports: Vec<ServicePort> = Vec::new();

        let pd_ports: Vec<ServicePort> = self
            .pd_container()
            .ports
            .expect("failed to find ports for pd container")
            .into_iter()
            .map(|p| ServicePort {
                name: p.name,
                port: p.container_port,
                ..Default::default()
            })
            .collect();
        let cmt_ports: Vec<ServicePort> = resources::cometbft_container()
            .ports
            .expect("failed to find ports for cometbft container")
            .into_iter()
            .map(|p| ServicePort {
                name: p.name,
                port: p.container_port,
                ..Default::default()
            })
            .collect();

        let mut db_ports: Vec<ServicePort> = Vec::new();
        if self.spec.enable_indexing.unwrap_or_default() {
            db_ports = resources::postgres_container()
                .ports
                .expect("failed to find ports for postgres container")
                .into_iter()
                .map(|p| ServicePort {
                    name: p.name,
                    port: p.container_port,
                    ..Default::default()
                })
                .collect();
        }

        ports.extend(pd_ports);
        ports.extend(cmt_ports);
        ports.extend(db_ports);

        Service {
            metadata: ObjectMeta {
                name: Some(self.release_name()),
                ..Default::default()
            },
            spec: Some(ServiceSpec {
                // Setting `None` will result in ClusterIP being automatically set.
                // Instead, we'll set the value to the string "None",
                // which m akes it a headless service, suitable for StatefulSets.
                cluster_ip: Some("None".to_string()),
                ports: Some(ports),
                ..Default::default()
            }),
            ..Default::default()
        }
    }

    /// Create [PersistentVolumeClaim]s for StatefulSet spec.
    pub fn volume_claim_templates(&self) -> Vec<PersistentVolumeClaim> {
        vec![
            PersistentVolumeClaim {
                metadata: ObjectMeta {
                    name: Some("penumbra-config".to_owned()),
                    labels: Some(crate::resources::labels()),
                    ..Default::default()
                },
                spec: Some(PersistentVolumeClaimSpec {
                    access_modes: Some(vec!["ReadWriteOnce".to_owned()]),
                    resources: Some(VolumeResourceRequirements {
                        requests: Some(BTreeMap::<String, Quantity>::from([(
                            "storage".to_owned(),
                            Quantity(crate::resources::DEFAULT_PVC_SIZE.to_owned()),
                        )])),
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
                ..Default::default()
            },
            PersistentVolumeClaim {
                metadata: ObjectMeta {
                    name: Some(crate::resources::DB_PVC_NAME.to_owned()),
                    labels: Some(crate::resources::labels()),
                    ..Default::default()
                },
                spec: Some(PersistentVolumeClaimSpec {
                    access_modes: Some(vec!["ReadWriteOnce".to_owned()]),
                    resources: Some(VolumeResourceRequirements {
                        requests: Some(BTreeMap::<String, Quantity>::from([(
                            "storage".to_owned(),
                            Quantity("1G".to_owned()),
                        )])),
                        ..Default::default()
                    }),
                    ..Default::default()
                }),
                ..Default::default()
            },
        ]
    }

    /// Generate environment variables for pd container, particularly the initContainer.
    pub fn pd_env(&self) -> Vec<EnvVar> {
        let mut env = Vec::<EnvVar>::new();
        // Bootstrap URL is required, since we need to talk to another node to join its network.
        env.push(EnvVar {
            name: "PENUMBRA_BOOTSTRAP_URL".to_owned(),
            // Must match what's honored by `pd network join --help`
            // TODO: use the pd built-in env vars
            // name: "PENUMBRA_PD_JOIN_URL".to_string(),
            value: Some(self.spec.bootstrap_url.clone()),
            value_from: None,
        });

        // Optionally load snapshot data from archive. Only affects init env.
        if let Some(u) = &self.spec.archive_url {
            env.push(EnvVar {
                // We intentionally don't use the built-in pd env var, because the archive
                // format has changed, and largely remains undocumented.
                // name: "PENUMBRA_PD_ARCHIVE_URL".to_string(),
                name: "PENUMBRA_CUSTOM_ARCHIVE_URL".to_owned(),
                value: Some(u.to_string()),
                ..Default::default()
            });
        }
        // Opt in to ABCI event indexing.
        if self.spec.enable_indexing.unwrap_or_default() {
            env.push(EnvVar {
                name: "PENUMBRA_COMETBFT_INDEXER".to_string(),
                value: Some("psql".to_string()),
                ..Default::default()
            });
            // TODO: disable psql indexer if indexing disabled.
            env.push(EnvVar {
                name: "COMETBFT_POSTGRES_CONNECTION_URL".to_string(),
                value: Some(
                    "postgresql://penumbra:penumbra@localhost:5432/penumbra?sslmode=disable"
                        .to_string(),
                ),
                ..Default::default()
            });
        }
        env
    }

    /// Create [Container] spec for `pd`, the Penumbra daemon.
    pub fn pd_container(&self) -> Container {
        let container_name = "pd".to_owned();
        Container {
            name: container_name,
            image: Some(format!("{PENUMBRA_IMAGE_REPO}:{PENUMBRA_IMAGE_TAG}")),
            command: Some(
                // TODO convert these options to env vars,
                // to make them more easily overrideable.
                vec![
                    "pd",
                    "start",
                    "--grpc-bind",
                    "0.0.0.0:8080",
                    "--metrics-bind",
                    "0.0.0.0:9000",
                    "--enable-expensive-rpc",
                ]
                .into_iter()
                .map(|x| x.to_owned())
                .collect(),
            ),
            env: Some(self.pd_env()),
            security_context: Some(SecurityContext {
                run_as_user: Some(1000),
                ..Default::default()
            }),
            ports: Some(vec![
                ContainerPort {
                    name: Some("pd-grpc".to_owned()),
                    container_port: 8080,
                    ..Default::default()
                },
                ContainerPort {
                    name: Some("pd-abci".to_owned()),
                    container_port: 26658,
                    ..Default::default()
                },
                ContainerPort {
                    name: Some("pd-metrics".to_owned()),
                    container_port: 9000,
                    ..Default::default()
                },
            ]),
            readiness_probe: Some(Probe {
                tcp_socket: Some(TCPSocketAction {
                    port: IntOrString::String("pd-grpc".to_owned()),
                    ..Default::default()
                }),
                ..Default::default()
            }),
            volume_mounts: Some(vec![VolumeMount {
                name: "penumbra-config".to_owned(),
                mount_path: "/home/penumbra/.penumbra".to_owned(),
                ..Default::default()
            }]),

            ..Default::default()
        }
    }
    /// Create [Container] spec for `pd-init`, for bootstrapping configuration
    /// from a remote node.
    pub fn pd_init_container(&self) -> Container {
        let container_name = "pd-init".to_owned();

        Container {
            name: container_name,
            image: Some(format!("{PENUMBRA_IMAGE_REPO}:{PENUMBRA_IMAGE_TAG}")),
            command: Some(
                vec!["bash", "/opt/penumbra/pd-init"]
                    .into_iter()
                    .map(|x| x.to_owned())
                    .collect(),
            ),
            env: Some(self.pd_env()),
            // Run as root during init, so we can shown to penumbra & cometbft users.
            // The application itself will run as a normal user.
            security_context: Some(SecurityContext {
                run_as_user: Some(0),
                run_as_group: Some(0),
                allow_privilege_escalation: Some(true),
                ..Default::default()
            }),
            volume_mounts: Some(vec![
                VolumeMount {
                    name: "penumbra-init".to_owned(),
                    mount_path: "/opt/penumbra".to_owned(),
                    ..Default::default()
                },
                VolumeMount {
                    name: "penumbra-config".to_owned(),
                    mount_path: "/home/penumbra/.penumbra/".to_owned(),
                    ..Default::default()
                },
            ]),
            ..Default::default()
        }
    }

    /// Ensure that the cluster resources representing the CRD are removed.
    #[tracing::instrument(skip_all)]
    pub async fn cleanup(&self, client: &Client) -> Result<Action> {
        tracing::warn!("cleanup functionality only partially implmented");

        tracing::info!("deleting Statefulset");
        let sts_api: Api<StatefulSet> = Api::namespaced(client.clone(), DEFAULT_NAMESPACE);
        match sts_api.get(self.release_name().as_str()).await {
            Ok(_sts) => {
                let delete_params = DeleteParams::default();
                sts_api
                    .delete(self.release_name().as_str(), &delete_params)
                    .await?;
            }
            Err(_e) => {
                // Log a warning because this shouldn't happen.
                tracing::warn!("statefulset not found, skipping deletion");
            }
        }

        let svc_api: Api<Service> = Api::namespaced(client.clone(), DEFAULT_NAMESPACE);
        match svc_api.get(self.release_name().as_str()).await {
            Ok(_sts) => {
                let delete_params = DeleteParams::default();
                svc_api
                    .delete(self.release_name().as_str(), &delete_params)
                    .await?;
            }
            Err(_e) => {
                // Log a warning because this shouldn't happen.
                tracing::warn!("service not found, skipping deletion");
            }
        }

        Ok(Action::await_change())
    }

    /// Ensure that the CRD is adequately expressed in cluster resources.
    pub async fn reconcile(&self, client: &Client) -> Result<Action> {
        // We need a ConfigMap in order for the initContainer to run.
        let cm = resources::pd_init_script_configmap();
        let cm_api: Api<ConfigMap> = Api::namespaced(client.clone(), DEFAULT_NAMESPACE);
        // In lieu of a `get-or-create` method in the kube API, we'll match on a get() call,
        // and create if not found.
        match cm_api.get(crate::resources::PD_INIT_CONFIG_MAP_NAME).await {
            Ok(_) => {
                let patch = Patch::Merge(&cm);
                let params = PatchParams::default();
                cm_api
                    .patch(crate::resources::PD_INIT_CONFIG_MAP_NAME, &params, &patch)
                    .await?;
            }
            Err(_e) => {
                tracing::info!("creating {:?}", &cm);
                cm_api.create(&PostParams::default(), &cm).await?;
            }
        }

        // Generate a StatefulSet for the node.
        let ss = self.stateful_set();
        let ss_api: Api<StatefulSet> = Api::namespaced(client.clone(), DEFAULT_NAMESPACE);
        match ss_api.get(&self.release_name()).await {
            Ok(_ss_old) => {
                tracing::debug!("found existing statefulset, trying to patch it...");
                let patch = Patch::Merge(&ss);
                let params = PatchParams::default();
                let _ss_new = ss_api
                    .patch(self.release_name().as_str(), &params, &patch)
                    .await?;
            }
            Err(_) => {
                tracing::info!("no prior sts found, CREATING one");
                ss_api.create(&PostParams::default(), &ss).await?;
            }
        }

        // Generate a Service for the node.
        let svc = self.service();
        let svc_api: Api<Service> = Api::namespaced(client.clone(), DEFAULT_NAMESPACE);
        match svc_api.get(&self.release_name()).await {
            Ok(_svc_old) => {
                tracing::debug!("found existing service, trying to patch it...");
                let patch = Patch::Merge(&svc);
                let params = PatchParams::default();
                let _svc_new = svc_api
                    .patch(self.release_name().as_str(), &params, &patch)
                    .await?;
            }
            Err(_) => {
                tracing::info!("creating service");
                svc_api.create(&PostParams::default(), &svc).await?;
            }
        }
        // If no events were received, check back every 5 minutes
        Ok(Action::requeue(Duration::from_secs(5 * 60)))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn from_specs() {
        let fullnode = PenumbraNode::new(
            "foo",
            PenumbraNodeSpec {
                moniker: "foo".into(),
                ..Default::default()
            },
        );
        let ss = fullnode.stateful_set();
        assert_eq!(ss.metadata.name.unwrap(), fullnode.release_name());
    }
}
