[package]
name = "pindexer-db-wrangler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.96"
base64 = "0.22.1"
clap = { version = "4.5.30", features = ["derive"] }
inquire = "0.7.5"
k8s-openapi = { version = "0.24.0", features = ["v1_30"] }
reqwest = { version = "0.12.12", features = ["stream"] }
serde_json = "1.0.139"
tokio = "1.43.0"
tokio-stream = "0.1.17"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "ansi"] }
url = "2.5.4"
which = "7.0.2"

picturesque = { path = "../penumbra4/tools/picturesque/"}
tempfile = "3.17.1"
