# Display available options
help:
  @just --list

# Lint the rust code
check:
  cargo check --all-features --all-targets

# Clear out local data dirs
clean:
  rm -rf testnet-reindex-1 mainnet-reindex-1

# Run the reindex against PL testnet
testnet:
  rm -rf testnet-reindex-1
  RUST_LOG=pindexer_db_wrangler=debug cargo run -- \
    --penumbra-environment testnet \
    --working-directory testnet-reindex-1 \
    --cometbft-src-database-url "$pindexer_src_db_testnet" \
    --pindexer-dst-database-url "$pindexer_dst_db_testnet"

# Run the reindex against mainnet
mainnet:
  rm -rf mainnet-reindex-1
  RUST_LOG=pindexer_db_wrangler=debug cargo run -- \
    --penumbra-environment mainnet \
    --working-directory mainnet-reindex-1 \
    --cometbft-src-database-url "$pindexer_src_db_mainnet" \
    --pindexer-dst-database-url "$pindexer_dst_db_mainnet"
