---
apiVersion: v1
kind: Namespace
metadata:
  name: penumbra
---
apiVersion: penumbra.zone/v1alpha1
kind: PenumbraNode
metadata:
  name: phlebas
  namespace: penumbra
spec:
  moniker: phlebas
  # The "post-upgrade" archive reported wrong version, might not be correct.
  # archive_url: "https://artifacts.plinfra.net/penumbra-testnet-phobos-2/penumbra-node-archive-height-1459800-post-upgrade.tar.gz"
  archive_url: "https://artifacts.plinfra.net/penumbra-testnet-phobos-2/penumbra-node-archive-height-1507616.tar.gz"
  bootstrap_url: "https://rpc.testnet-preview.plinfra.net"
  network_name: testnet-preview
---
apiVersion: penumbra.zone/v1alpha1
kind: PenumbraNode
metadata:
  name: norbert
  namespace: penumbra
spec:
  moniker: norbert
  # The "post-upgrade" archive reported wrong version, might not be correct.
  # archive_url: "https://artifacts.plinfra.net/penumbra-testnet-phobos-2/penumbra-node-archive-height-1459800-post-upgrade.tar.gz"
  archive_url: "https://artifacts.plinfra.net/penumbra-testnet-phobos-2/penumbra-node-archive-height-1507616.tar.gz"
  bootstrap_url: "https://rpc.testnet-preview.plinfra.net"
  network_name: testnet-preview
  enable_indexing: true
